from flask import Flask, jsonify, request
from Controllers.Users import Users
from Controllers.Messages import Messages

app = Flask(__name__)

@app.route('/app')

@app.route('/app/new_users', methods = ['POST'])
def new_user():
    if request.method == 'POST':
        user_data = request.get_json()
        return Users().addNewUser1(user_data)
    else:
        return jsonify('Method not allowed.'), 405
    
@app.route('/app/mod_users', methods = ['PUT'])
def mod_user():
    if request.method == 'PUT':
        new_user_info = request.get_json()
        return Users().updateUsers1(new_user_info)
    else:
        return jsonify('Method not allowed.'), 405

@app.route('/app/existing_users/<int:user_id>', methods = ['GET', 'DELETE'])
def existing_users(user_id):
    if request.method == 'GET':
        return Users().getUsersById1(user_id)
    elif request.method == 'DELETE':
        return Users().deleteUsers1(user_id)
    else:
        return jsonify('Method not allowed'), 405

@app.route('/app/new_message', methods = ['POST'])
def new_message():
    if request.method == 'POST':
        new_message = request.get_json()
        return Messages().sendNewMessage1(new_message)
    else:
        return jsonify('Method not allowed.'), 405

@app.route('/app/mod_messages', methods = ['PUT'])
def mod_messages():
    if request.method == 'PUT':
        new_message = request.get_json()
        return Messages().updateMessage1(new_message)
    else:
        return jsonify('Method not allowed.'), 405

@app.route('/app/existing_messages/<int:message_id>', methods = ['GET', 'DELETE'])
def existing_messages(message_id):
    if request.method == 'GET':
        return Messages().getMessageById1(message_id)
    elif request.method == 'DELETE':
        return Messages().deleteMessage1(message_id)
    else:
        return jsonify('Method is not allowed.'), 405

#Changes:
#Use query params for GET, instead of get_json() all the time
#Move jsonify to controllers
#Use only one query instead of two (MySQL)
#Autogenerated values for ids
#Change 'GET' for 'delete'
#<int: message_id>